export const sampleProducts = [
  {
    name: "iPhone 14 Pro",
    slug: "iphone-14-pro",
    banner: "https://example.com/iphone-14-pro.jpg",
    description: "The latest iPhone with advanced features.",
    price: 999,
    discountPrice: 899,
    category: "smartphone",
    subcategories: ["iOS", "Flagship Phones"],
    features: ["5G", "Triple Camera", "120Hz Display"],
    colors: [
      { name: "Deep Purple", hex: "#3c3b6e" },
      { name: "Gold", hex: "#ffd700" },
    ],
    brand: "Apple",
    stock: 50,
    sku: "APL-IP14-PRO-APL-IP14-PRO",
    ratings: 4.8,
    feature: true,
    numOfReviews: 200,
    sold: 150,
  },
  {
    name: "iPhone 14 Pro",
    slug: "iphone-14-pro",
    banner: "https://example.com/iphone-14-pro.jpg",
    description: "The latest iPhone with advanced features.",
    price: 999,
    discountPrice: 899,
    category: "smartphone",
    subcategories: ["iOS", "Flagship Phones"],
    features: ["5G", "Triple Camera", "120Hz Display"],
    colors: [
      { name: "Deep Purple", hex: "#3c3b6e" },
      { name: "Gold", hex: "#ffd700" },
    ],
    brand: "Apple",
    stock: 50,
    sku: "APL-IP14-PRO-h",
    ratings: 4.8,
    feature: true,
    numOfReviews: 200,
    sold: 150,
  },
  {
    name: "Samsung Galaxy S23",
    slug: "samsung-galaxy-s23",
    banner: "https://example.com/galaxy-s23.jpg",
    description: "Experience the next generation of smartphones.",
    price: 899,
    discountPrice: 849,
    category: "smartphone",
    subcategories: ["Android", "Flagship Phones"],
    features: ["8K Video", "Snapdragon 8 Gen 2", "Dynamic AMOLED 2X"],
    colors: [
      { name: "Phantom Black", hex: "#000000" },
      { name: "Cream", hex: "#F5F5DC" },
    ],
    brand: "Samsung",
    stock: 100,
    sku: "SMS-S23-BLK",
    ratings: 4.5,
    feature: true,
    numOfReviews: 150,
    sold: 120,
  },
  {
    name: "Google Pixel 7 Pro",
    slug: "google-pixel-7-pro",
    banner: "https://example.com/google-pixel-7-pro.jpg",
    description: "Google's most advanced smartphone with AI features.",
    price: 799,
    discountPrice: 749,
    category: "smartphone",
    subcategories: ["Android", "Photography"],
    features: ["Tensor G2", "Magic Eraser", "120Hz Display"],
    colors: [
      { name: "Obsidian", hex: "#000000" },
      { name: "Snow", hex: "#ffffff" },
    ],
    brand: "Google",
    stock: 80,
    sku: "GOO-P7-PRO",
    ratings: 4.6,
    feature: true,
    numOfReviews: 120,
    sold: 90,
  },

  // 2. Audio Products
  {
    name: "Sony WH-1000XM5",
    slug: "sony-wh-1000xm5",
    banner: "https://example.com/sony-headphones.jpg",
    description: "Industry-leading noise-canceling headphones.",
    price: 399,
    category: "handsfree,headphon",
    subcategories: ["Bluetooth", "Noise Cancelling"],
    features: ["30-Hour Battery Life", "Quick Charge", "Hi-Res Audio"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    brand: "Sony",
    stock: 75,
    sku: "SON-WH1000XM5",
    ratings: 4.9,
    feature: true,
    numOfReviews: 300,
    sold: 200,
  },
  {
    name: "AirPods Pro 2nd Gen",
    slug: "airpods-pro-2",
    banner: "https://example.com/airpods-pro-2.jpg",
    description: "Apple's most advanced AirPods with spatial audio.",
    price: 249,
    category: "handsfree,headphon",
    subcategories: ["Bluetooth", "Wireless"],
    features: ["Active Noise Cancellation", "MagSafe Charging", "H2 Chip"],
    colors: [{ name: "White", hex: "#ffffff" }],
    brand: "Apple",
    stock: 120,
    sku: "APL-APP2",
    ratings: 4.7,
    feature: true,
    numOfReviews: 180,
    sold: 140,
  },

  // 3. Laptop Products
  {
    name: "MacBook Pro 16",
    slug: "macbook-pro-16",
    banner: "https://example.com/macbook-pro-16.jpg",
    description: "Apple's ultimate laptop for professionals.",
    price: 2499,
    discountPrice: 2299,
    category: "laptop,tablet,ipad ...",
    subcategories: ["Laptops", "Accessories"],
    features: ["M2 Max Chip", "Liquid Retina XDR", "32GB RAM"],
    colors: [
      { name: "Space Gray", hex: "#4B4B4B" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    brand: "Apple",
    stock: 25,
    sku: "APL-MBP-16",
    ratings: 4.9,
    feature: true,
    numOfReviews: 90,
    sold: 70,
  },
  {
    name: "Dell Inspiron 15",
    slug: "dell-inspiron-15",
    banner: "https://example.com/dell-inspiron-15.jpg",
    description: "A reliable laptop for everyday use.",
    price: 599,
    category: "laptop,tablet,ipad ...",
    subcategories: ["Laptops", "Budget"],
    features: ["Intel i5", "15.6-inch FHD", "8GB RAM"],
    colors: [{ name: "Platinum Silver", hex: "#E5E5E5" }],
    brand: "Dell",
    stock: 45,
    sku: "DEL-INS-15",
    ratings: 4.4,
    feature: false,
    numOfReviews: 70,
    sold: 40,
  },

  // 4. Gaming Products
  {
    name: "PlayStation 5",
    slug: "playstation-5",
    banner: "https://example.com/ps5.jpg",
    description: "Sony's latest gaming console with incredible graphics.",
    price: 499,
    category: "gaming",
    subcategories: ["Consoles"],
    features: ["4K Gaming", "120FPS", "SSD Storage"],
    colors: [{ name: "White", hex: "#ffffff" }],
    brand: "Sony",
    stock: 20,
    sku: "SON-PS5",
    ratings: 4.9,
    feature: true,
    numOfReviews: 500,
    sold: 450,
  },
  {
    name: "Xbox Series X",
    slug: "xbox-series-x",
    banner: "https://example.com/xbox-series-x.jpg",
    description: "The fastest and most powerful Xbox ever.",
    price: 499,
    category: "gaming",
    subcategories: ["Consoles"],
    features: ["8K HDR", "1TB SSD", "Game Pass"],
    colors: [{ name: "Black", hex: "#000000" }],
    brand: "Microsoft",
    stock: 30,
    sku: "MS-XBX",
    ratings: 4.8,
    feature: true,
    numOfReviews: 400,
    sold: 300,
  },
];
