import ContactForm from "@/components/contact/ContactForm";
import { Metadata } from "next";
import { auth } from "../../../../auth";
import { redirect } from "next/navigation";
export const metadata: Metadata = {
  title: "Call, email, chat or meet us in this location | tech-store",
  description: "Generated by create next app",
};

const ContactPage = async () => {
  const session = await auth();

  if (!session) redirect("/user-login");

  return (
    <>
      <div className='my-20 lg:w-[90vw] w-[95vw] mx-auto border rounded'>
        <ContactForm />
      </div>
    </>
  );
};

export default ContactPage;
