export const phoneBrands = [
  { name: "Apple", link: "/iphones" },
  { name: "Samsung", link: "/samsung-phones" },
  { name: "Google", link: "/google-phones" },
  { name: "Xiaomi", link: "/xiami-phones" },
  { name: "Oppo", link: "/oppo-phones" },
  { name: "Vivo", link: "/vivo-phones" },
  { name: "OnePlus", link: "/onepus-phones" },
  { name: "Huawei", link: "/huawei-phones" },
  { name: "Sony", link: "/sony-phones" },
  { name: "Motorola", link: "/motorola-phones" },
  { name: "Nokia", link: "/nokia-phones" },
  { name: "Realme", link: "/realme-phones" },
  { name: "Asus", link: "/asus-phones" },
  { name: "Lenovo", link: "/lenono-phones" },
  { name: "Honor", link: "/honor-phones" },
  { name: "LG", link: "/lg-phones" },
  { name: "ZTE", link: "/zte-phones" },
  { name: "Meizu", link: "/meizu-phones" },
  { name: "Infinix", link: "/infinix-phones" },
  { name: "Tecno", link: "/tecno-phones" },
  { name: "Alcatel", link: "/alcatel-phones" },
  { name: "BlackBerry", link: "/blackberry-phones" },
  { name: "iQOO", link: "/iqoo-phones" },
  { name: "Micromax", link: "/micromax-phones" },
  { name: "Panasonic", link: "/panasonic-phones" },
];

export const laptopTabletBrands = [
  { name: "Apple", link: "/" },
  { name: "Samsung", link: "/" },
  { name: "Dell", link: "/" },
  { name: "HP", link: "/" },
  { name: "Lenovo", link: "/" },
  { name: "Asus", link: "/" },
  { name: "Microsoft Surface", link: "/" },
  { name: "Acer", link: "/" },
  { name: "Razer", link: "/" },
  { name: "MSI", link: "/" },
  { name: "Google Pixel", link: "/" },
  { name: "Huawei", link: "/" },
  { name: "LG", link: "/" },
  { name: "Toshiba", link: "/" },
  { name: "Sony Vaio", link: "/" },
  { name: "Xiaomi", link: "/" },
  { name: "Panasonic", link: "/" },
  { name: "Chromebook", link: "/" },
  { name: "Eve", link: "/" },
  { name: "Honor", link: "/" },
];

export const watchBrands = [
  { name: "Rolex", link: "/" },
  { name: "Omega", link: "/" },
  { name: "Tag Heuer", link: "/" },
  { name: "Casio", link: "/" },
  { name: "Seiko", link: "/" },
  { name: "Patek Philippe", link: "/" },
  { name: "Audemars Piguet", link: "/" },
  { name: "Breitling", link: "/" },
  { name: "Panerai", link: "/" },
  { name: "Tissot", link: "/" },
  { name: "Longines", link: "/" },
  { name: "Citizen", link: "/" },
  { name: "Apple Watch", link: "/" },
  { name: "Fossil", link: "/" },
  { name: "Michael Kors", link: "/" },
  { name: "Bvlgari", link: "/" },
  { name: "IWC Schaffhausen", link: "/" },
  { name: "Jaeger-LeCoultre", link: "/" },
  { name: "Hublot", link: "/" },
  { name: "Tag Heuer", link: "/" },
];

export const computerBrands = [
  { name: "Apple", link: "/" },
  { name: "Dell", link: "/" },
  { name: "HP", link: "/" },
  { name: "Lenovo", link: "/" },
  { name: "Asus", link: "/" },
  { name: "Acer", link: "/" },
  { name: "Microsoft", link: "/" },
  { name: "Samsung", link: "/" },
  { name: "Razer", link: "/" },
  { name: "MSI", link: "/" },
  { name: "Google", link: "/" },
  { name: "Toshiba", link: "/" },
  { name: "Alienware", link: "/" },
  { name: "Huawei", link: "/" },
  { name: "LG", link: "/" },
  { name: "Xiaomi", link: "/" },
  { name: "Panasonic", link: "/" },
  { name: "IBM", link: "/" },
  { name: "Fujitsu", link: "/" },
  { name: "Compaq", link: "/" },
];

export const networkConnectivityBrands = [
  { name: "Cisco", link: "/" },
  { name: "Netgear", link: "/" },
  { name: "TP-Link", link: "/" },
  { name: "Linksys", link: "/" },
  { name: "Huawei", link: "/" },
  { name: "Aruba Networks", link: "/" },
  { name: "Ubiquiti Networks", link: "/" },
  { name: "Juniper Networks", link: "/" },
  { name: "Zyxel", link: "/" },
  { name: "D-Link", link: "/" },
  { name: "Samsung Networks", link: "/" },
  { name: "MikroTik", link: "/" },
  { name: "Ruckus Wireless", link: "/" },
  { name: "Fortinet", link: "/" },
  { name: "Alcatel-Lucent", link: "/" },
  { name: "Check Point", link: "/" },
  { name: "Extreme Networks", link: "/" },
  { name: "Arista Networks", link: "/" },
  { name: "Broadcom", link: "/" },
  { name: "Qualcomm", link: "/" },
];

export const homeApplianceBrands = [
  { name: "Samsung", link: "/" },
  { name: "LG", link: "/" },
  { name: "Whirlpool", link: "/" },
  { name: "GE Appliances", link: "/" },
  { name: "Bosch", link: "/" },
  { name: "Philips", link: "/" },
  { name: "Panasonic", link: "/" },
  { name: "Sony", link: "/" },
  { name: "KitchenAid", link: "/" },
  { name: "Frigidaire", link: "/" },
  { name: "Maytag", link: "/" },
  { name: "Haier", link: "/" },
  { name: "Electrolux", link: "/" },
  { name: "Sharp", link: "/" },
  { name: "Toshiba", link: "/" },
  { name: "Miele", link: "/" },
  { name: "Viking", link: "/" },
  { name: "Samsung SmartThings", link: "/" },
  { name: "De'Longhi", link: "/" },
  { name: "Dyson", link: "/" },
];

export const audioBrands = [
  { name: "Bose", link: "/" },
  { name: "Sony", link: "/" },
  { name: "Sennheiser", link: "/" },
  { name: "JBL", link: "/" },
  { name: "Bang & Olufsen", link: "/" },
  { name: "Audio-Technica", link: "/" },
  { name: "Shure", link: "/" },
  { name: "Harman Kardon", link: "/" },
  { name: "Marshall", link: "/" },
  { name: "Beats by Dre", link: "/" },
  { name: "Skullcandy", link: "/" },
  { name: "AKG", link: "/" },
  { name: "Pioneer", link: "/" },
  { name: "Klipsch", link: "/" },
  { name: "Creative Labs", link: "/" },
  { name: "Yamaha", link: "/" },
  { name: "Etymotic", link: "/" },
  { name: "V-Moda", link: "/" },
  { name: "Razer", link: "/" },
  { name: "Koss", link: "/" },
];

export const videoBrands = [
  { name: "Sony", link: "/" },
  { name: "Samsung", link: "/" },
  { name: "LG", link: "/" },
  { name: "Panasonic", link: "/" },
  { name: "Sharp", link: "/" },
  { name: "Vizio", link: "/" },
  { name: "TCL", link: "/" },
  { name: "Philips", link: "/" },
  { name: "JVC", link: "/" },
  { name: "BenQ", link: "/" },
  { name: "Epson", link: "/" },
  { name: "Acer", link: "/" },
  { name: "ViewSonic", link: "/" },
  { name: "Hisense", link: "/" },
  { name: "Roku", link: "/" },
  { name: "Xiaomi", link: "/" },
  { name: "Sanyo", link: "/" },
  { name: "Toshiba", link: "/" },
  { name: "Cinemood", link: "/" },
  { name: "InFocus", link: "/" },
];

export const gamingBrands = [
  { name: "Sony PlayStation", link: "/" },
  { name: "Microsoft Xbox", link: "/" },
  { name: "Nintendo", link: "/" },
  { name: "Razer", link: "/" },
  { name: "Logitech", link: "/" },
  { name: "Corsair", link: "/" },
  { name: "Alienware", link: "/" },
  { name: "MSI", link: "/" },
  { name: "SteelSeries", link: "/" },
  { name: "HyperX", link: "/" },
  { name: "Turtle Beach", link: "/" },
  { name: "Astro Gaming", link: "/" },
  { name: "Acer Predator", link: "/" },
  { name: "BenQ Zowie", link: "/" },
  { name: "EVGA", link: "/" },
  { name: "NVIDIA", link: "/" },
  { name: "AMD", link: "/" },
  { name: "Seagate Gaming", link: "/" },
  { name: "Logitech G", link: "/" },
  { name: "Thermaltake", link: "/" },
];

export const jewelryBrands = [
  { name: "Tiffany & Co.", link: "/" },
  { name: "Cartier", link: "/" },
  { name: "Harry Winston", link: "/" },
  { name: "Bvlgari", link: "/" },
  { name: "Van Cleef & Arpels", link: "/" },
  { name: "Chopard", link: "/" },
  { name: "Piaget", link: "/" },
  { name: "David Yurman", link: "/" },
  { name: "Rolex", link: "/" },
  { name: "Pandora", link: "/" },
  { name: "Swarovski", link: "/" },
  { name: "Blue Nile", link: "/" },
  { name: "Montblanc", link: "/" },
  { name: "Boucheron", link: "/" },
  { name: "Mikimoto", link: "/" },
  { name: "IWC Schaffhausen", link: "/" },
  { name: "Jaeger-LeCoultre", link: "/" },
  { name: "Chanel", link: "/" },
  { name: "Harry Winston", link: "/" },
  { name: "Graff", link: "/" },
];

export const beautyBrands = [
  { name: "Chanel", link: "/" },
  { name: "Dior", link: "/" },
  { name: "Estée Lauder", link: "/" },
  { name: "MAC Cosmetics", link: "/" },
  { name: "Lancôme", link: "/" },
  { name: "Yves Saint Laurent", link: "/" },
  { name: "NARS", link: "/" },
  { name: "Benefit Cosmetics", link: "/" },
  { name: "Fenty Beauty", link: "/" },
  { name: "Urban Decay", link: "/" },
  { name: "Too Faced", link: "/" },
  { name: "Charlotte Tilbury", link: "/" },
  { name: "Bobbi Brown", link: "/" },
  { name: "Shiseido", link: "/" },
  { name: "Kiehl's", link: "/" },
  { name: "L'Oréal", link: "/" },
  { name: "Maybelline", link: "/" },
  { name: "Revlon", link: "/" },
  { name: "Tarte Cosmetics", link: "/" },
  { name: "Clinique", link: "/" },
];

export const headphoneBrands = [
  { name: "Sony", link: "/" },
  { name: "Bose", link: "/" },
  { name: "Sennheiser", link: "/" },
  { name: "JBL", link: "/" },
  { name: "Beats by Dre", link: "/" },
  { name: "Audio-Technica", link: "/" },
  { name: "Bang & Olufsen", link: "/" },
  { name: "Shure", link: "/" },
  { name: "Samsung", link: "/" },
  { name: "Skullcandy", link: "/" },
  { name: "Philips", link: "/" },
  { name: "Plantronics", link: "/" },
  { name: "HyperX", link: "/" },
  { name: "Razer", link: "/" },
  { name: "Anker Soundcore", link: "/" },
  { name: "AKG", link: "/" },
  { name: "OnePlus", link: "/" },
  { name: "Marshall", link: "/" },
  { name: "V-Moda", link: "/" },
  { name: "Pioneer", link: "/" },
];

export const categoriesData = [
  {
    category: "smartphone",
    subCategories: [
      "Android",
      "iOS",
      "Phone Accessories",
      "Budget Phones",
      "Flagship Phones",
      "Charger (cable, Canduncer ...)",
    ],
  },
  {
    category: "phone accessories",
    subCategories: [
      "Chargers",
      "Cables",
      "Cases",
      "Screen Protectors",
      "Mounts",
    ],
  },
  {
    category: "handsfree,headphone",
    subCategories: [
      "Bluetooth",
      "Wired",
      "Noise Cancelling",
      "Gaming Headsets",
      "Sports",
    ],
  },
  {
    category: "laptop,tablet,ipad ...",
    subCategories: [
      "Laptops",
      "Tablets",
      "iPads",
      "2-in-1 Devices",
      "Laptop Accessories",
    ],
  },
  {
    category: "laptop accessories",
    subCategories: [
      "Laptop Bags",
      "Cooling Pads",
      "Docking Stations",
      "Laptop Stands",
    ],
  },
  {
    category: "home appliance",
    subCategories: [
      "Refrigerators",
      "Microwaves",
      "Washing Machines",
      "Vacuum Cleaners",
      "Air Conditioners",
    ],
  },
  {
    category: "jeweleries",
    subCategories: ["Necklaces", "Rings", "Bracelets", "Earrings", "Watches"],
  },
  {
    category: "computer",
    subCategories: ["Desktops", "Monitors", "Keyboards", "Mice", "Components"],
  },
  {
    category: "computer accessories",
    subCategories: [
      "External Hard Drives",
      "USB Hubs",
      "Cooling Fans",
      "Adapters",
      "Webcams",
    ],
  },
  {
    category: "watches",
    subCategories: [
      "Smartwatches",
      "Analog Watches",
      "Digital Watches",
      "Luxury Watches",
      "Fitness Trackers",
    ],
  },
  {
    category: "networks & connectivities",
    subCategories: [
      "WiFi Routers",
      "Modems",
      "Network Cables",
      "Adapters",
      "Range Extenders",
    ],
  },
  {
    category: "video",
    subCategories: [
      "Projectors",
      "Cameras",
      "Camcorders",
      "Video Editing Tools",
      "Video Accessories",
    ],
  },
  {
    category: "audio",
    subCategories: [
      "Speakers",
      "Soundbars",
      "Microphones",
      "Studio Equipment",
      "Home Audio Systems",
    ],
  },
  {
    category: "gaming",
    subCategories: [
      "Consoles",
      "PC Gaming",
      "Gaming Chairs",
      "VR Gaming",
      "Game Accessories",
    ],
  },
  {
    category: "beauty",
    subCategories: [
      "Skincare",
      "Haircare",
      "Makeup",
      "Fragrances",
      "Tools & Accessories",
    ],
  },
  {
    category: "others",
    subCategories: [
      "Office Supplies",
      "Stationery",
      "Toys",
      "Outdoor Gear",
      "Miscellaneous",
      "others...",
    ],
  },
  {
    category: "Gift Cards",
    subCategories: [
      "mother day",
      "father day",
      "women day",
      "girl day",
      "birthday",
      "others ...",
    ],
  },
];
